<?php
return array(
	//'配置项'=>'配置值'
    //设置模板替换变量
    'TMPL_PARSE_STRING'=>array(
        '__JS__'=>__ROOT__.'/Public/'.MODULE_NAME.'/js',
        '__IMG__'=>__ROOT__.'/Public/'.MODULE_NAME.'/img',
        '__CSS__'=>__ROOT__.'/Public/'.MODULE_NAME.'/css',
        '__UPLOAD__'=>__ROOT__.'/Public/'.MODULE_NAME.'/uploadify',
    ),
    //设置cookie密钥
    'COOKIE_KEY'=>'www.djl52102.top',
    //默认错误跳转对应的模板
    'TMPL_ACTION_ERROR'=>'Public/jump',
    //默认成功跳转对应的模板
    'TMPL_ACTION_SUCCESS'=>'Public/jump',
    //上传文件目录
    'UPLOAD_PATH'=>'./Uploads/',
    //页面调试
    //'SHOW_PAGE_TRACE'=>true,
    //头像上传路径
    'FACE_PATH'=>'./Uploads/face/',
    //启用路由规则
    'URL_ROUTER_ON'=>true,
    //配置路由规则
    'URL_ROUTE_RULES'=>array(
        'i/:domain'=>'Space/index'
    )
);